kind: Namespace
apiVersion: v1
metadata: 
  name: teama
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: pyapp
  namespace: teama
spec:
  replicas: 2  
  selector:
    matchLabels:
      run: test
  template:   ## this is the pod template
    metadata:
      labels:
        run: test
    spec:
      restartPolicy: Always # Never
      containers:  ## app containers
        - name: tcont
          image: docker.io/lerndevops/samples:pyapp-v2
          ports:
            - name: http 
              containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: pyapp
  namespace: teama
spec:
  type: NodePort
  selector:
    run: test
  ports:
    - port: 80
      targetPort: 3000
