apiVersion: v1
kind: PersistentVolume
metadata:
  name: springboot-app-pv
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle ## Retain / Delete
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /dbdata

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: springboot-app-pvc
spec:
  volumeName: springboot-app-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
       - image: lerndevops/samples:mongodb
         name: mongo
         volumeMounts:
           - name: pv
             mountPath: "/data/db"
      volumes:
       - name: pv
         persistentVolumeClaim:
            claimName: springboot-app-pvc

---
apiVersion: v1
kind: Service
metadata:
   name: mongo
spec:
   type: ClusterIP
   ports:
    - port: 27017
      targetPort: 27017
   selector:
     app: mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: lerndevops/samples:springboot-app
        name: springboot-app
        
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-svc
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 8080
  selector:
    app: myapp
