apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: readonly-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["pods", "replicasets"]
  verbs: ["get", "watch", "list"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create", "delete"]
  #verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
